version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd1!
      POSTGRES_DB: hello_world_db

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:P@ssw0rd1!@postgres:5432/hello_world_db?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  redis_exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/helloworld
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: P@ssw0rd1!
      REDIS_HOST: redis
      REDIS_DB: 0
      REDIS_URL: redis://redis
      REDIS_PORT: 6379
      APPNAME_DATABASE_PASSWORD: P@ssw0rd1!
      SECRET_KEY_BASE_DUMMY: 1

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter
      - web
      - redis_exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3010:3010"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  grafana_data:
  
