global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'HelloWorld-Monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.17.0.2:9323']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'web'
    static_configs:
      - targets: ['web:9394']

